# This docker-compose file preparing database sql server images where unit tests will be run.

version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Strong_Pass123
      ACCEPT_EULA: 'Y'
    ports:
      - "11433:1433"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Strong_Pass123
    ports:
      - "15432:5432"

