version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Strong_Pass123
      ACCEPT_EULA: 'Y'
    ports:
      - "11433:1433"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Strong_Pass123
    ports:
      - "15432:5432"



# version: '3.4'

# services:
#   testproject1:
#     image: ${DOCKER_REGISTRY-}testproject1
#     build:
#       context: .
#       dockerfile: TestProject1/Dockerfile
