# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: Strong_Pass123
          ACCEPT_EULA: 'Y'
          #MSSQL_PID: Express
        ports:
          - 1433:1433
        options: --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"  --health-interval 10s --health-timeout 5s --health-retries 5

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Strong_Pass123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PUBLISH_TOKEN}}
      SOLUTION_PATH: 'src/EasySqlFlow.sln'
      ConnectionStrings__SQLSERVER: Server=localhost,1433;Initial Catalog=master;User Id=sa;Password=Strong_Pass123;TrustServerCertificate=True;Encrypt=True;
      ConnectionStrings__POSTGRESQL: Server=localhost;Port=5432;Database=postgres;User ID=postgres;password=Strong_Pass123;

    steps:

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/zatuliveter/index.json

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }} 

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Debug #debug required to run unit tests

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal

    - name: Create the package
      run: dotnet pack ${{ env.SOLUTION_PATH }} --configuration Release

    - name: Publish the package to GPR
      run: dotnet nuget push bin/Release/*.nupkg
      