name: CICD

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  compile:
    
    name: Build > Test > Publish

    runs-on: ubuntu-latest

    env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PUBLISH_TOKEN}}
      SOLUTION_PATH: 'src/DbLive.sln'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 #required for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/zatuliveter/index.json # nuget publish url

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: .github/GitVersion.yml
        updateAssemblyInfo: true
      
    - name: Update NuGet package version
      run: |
        echo "Updating version to $GitVersion_SemVer in project files"
        find . -name '*.csproj' -print0 | xargs -0 sed -i "s/<Version>.*<\/Version>/<Version>$GitVersion_SemVer<\/Version>/g"
    
    - name: Semver
      run: echo $GitVersion_SemVer

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }} 

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --filter "Category!=LocalOnly" --no-restore --no-build --verbosity normal

    - name: Create DbLive package
      run: dotnet pack 'src/DbLive/DbLive.csproj' --no-restore --configuration Release

    - name: Create DbLive.MSSQL package
      run: dotnet pack 'src/DbLive.MSSQL/DbLive.MSSQL.csproj' --no-restore --configuration Release

    - name: Create DbLive.xunit package
      run: dotnet pack 'src/DbLive.xunit/DbLive.xunit.csproj' --no-restore --configuration Release

    - name: Publish packages
      run: dotnet nuget push **/bin/Release/*.nupkg
     
    - name: Create git tag
      if: github.ref == 'refs/heads/main'
      run: git tag $GitVersion_SemVer

    - name: Push git tag
      if: github.ref == 'refs/heads/main'
      run: git push origin $GitVersion_SemVer