name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  gitversion:

    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: Strong_Pass123
          ACCEPT_EULA: 'Y'
          #MSSQL_PID: Express
        ports:
          - 1433:1433
        options: --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"  --health-interval 10s --health-timeout 5s --health-retries 5

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Strong_Pass123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PUBLISH_TOKEN}}
      SOLUTION_PATH: 'src/EasySqlFlow.sln'
      ConnectionStrings__SQLSERVER: Server=localhost,1433;Initial Catalog=master;User Id=sa;Password=Strong_Pass123;TrustServerCertificate=True;Encrypt=True;
      ConnectionStrings__POSTGRESQL: Server=localhost;Port=5432;Database=postgres;User ID=postgres;password=Strong_Pass123;

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 #required for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/zatuliveter/index.json

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: .github/GitVersion.yml
        updateAssemblyInfo: true
      
    - name: Update NuGet package version
      run: |
        echo "Updating version to $GITVERSION_SEMVER in project files"
        find . -name '*.csproj' -print0 | xargs -0 sed -i "s/<Version>.*<\/Version>/<Version>$GITVERSION_SEMVER<\/Version>/g"
    
    - name: Semver
      run: echo $GITVERSION_SEMVER

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }} 

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --verbosity normal #--no-build

    - name: Create EasyFlow package
      run: dotnet pack 'src/EasyFlow/EasyFlow.csproj' --no-restore --configuration Release

    - name: Create EasyFlow.MSSQL package
      run: dotnet pack 'src/EasyFlow.MSSQL/EasyFlow.MSSQL.csproj' --no-restore --configuration Release

    - name: Publish packages
      run: dotnet nuget push **/bin/Release/*.nupkg
     
    - name: Create git tag
      if: github.ref == 'refs/heads/main'
      run: git tag $GITVERSION_SEMVER

    - name: Push git tag
      if: github.ref == 'refs/heads/main'
      run: git push origin $GITVERSION_SEMVER