name: CICD

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  compile:
    
    name: Build > Test > Publish

    runs-on: ubuntu-latest

    env:
      NUGET_ORG_AUTH_TOKEN: ${{secrets.NUGET_ORG_AUTH_TOKEN}}
      SOLUTION_PATH: 'src/DbLive.sln'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x        

    - name: Install GitVersion (tool)
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: .github/GitVersion.yml
        updateAssemblyInfo: false

    - name: Show computed versions
      run: |
        echo "GitVersion FullSemVer: ${{ steps.gitversion.outputs.FullSemVer }}"
        echo "GitVersion SemVer:     ${{ steps.gitversion.outputs.SemVer }}"
        echo "GitVersion NuGetV2:    ${{ steps.gitversion.outputs.NuGetVersionV2 }}"

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }} 

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore -p:ContinuousIntegrationBuild=true -p:Version=${{ steps.gitversion.outputs.FullSemVer }}

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --filter "Category!=LocalOnly" --no-restore --no-build --verbosity normal

    - name: Create DbLive package
      run: dotnet pack 'src/DbLive/DbLive.csproj' --no-restore --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

    - name: Create DbLive.xunit package
      run: dotnet pack 'src/DbLive.xunit/DbLive.xunit.csproj' --no-restore --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

    - name: Create DbLive.MSSQL package
      run: dotnet pack 'src/DbLive.MSSQL/DbLive.MSSQL.csproj' --no-restore --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

    - name: Create DbLive.PostgreSQL package
      run: dotnet pack 'src/DbLive.PostgreSQL/DbLive.PostgreSQL.csproj' --no-restore --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

    - name: Publish packages
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet nuget push **/bin/Release/*.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key $NUGET_ORG_AUTH_TOKEN \
          --skip-duplicate

    - name: Configure git
      if: github.ref == 'refs/heads/main'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Create git tag
      if: github.ref == 'refs/heads/main'
      run: git tag ${{ steps.gitversion.outputs.SemVer }}

    - name: Push git tag
      if: github.ref == 'refs/heads/main'
      run: git push origin ${{ steps.gitversion.outputs.SemVer }}