# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: Strong_Pass123
          ACCEPT_EULA: 'Y'
          #MSSQL_PID: Express
        ports:
          - '1433:1433'
        options: --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"  --health-interval 10s --health-timeout 5s --health-retries 5


      # sql-server:
      #   # Docker Hub image
      #   image: mcr.microsoft.com/mssql/server:2022-latest
      #   env:
      #     ACCEPT_EULA: Y
      #     SA_PASSWORD: 'Pr1sm4_Pr1sm4'
      #   # Maps tcp port 1433 on service container to the host
      #   ports:
      #     - '1433:1433'
      #   options: --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"  --health-interval 10s --health-timeout 5s --health-retries 5
    
    # services:
    #   sql-server:
    #     image: mcr.microsoft.com/mssql/server
    #     env:
    #       SA_PASSWORD: SAPass123
    #       ACCEPT_EULA: Y
    #       MSSQL_PID: Express
    #     options: --health-cmd "sqlcmd -Usa -SAPass123 -Q \"SELECT 1\""
    
    env:
      SOLUTION_PATH: 'src/EasySqlFlow.sln'
      SqlServer: Server=localhost,1433;Initial Catalog=master;User Id=sa;Password=StrongPass123;TrustServerCertificate=True;Encrypt=True;

    steps:

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }} 

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal
