name: GitVersion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitversion:
    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: 'src/EasySqlFlow.sln'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 #required for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: gitvertion-config.yml
        updateAssemblyInfo: true
    
    - name: Semver
      run: echo $GITVERSION_SEMVER

    # - name: Install GitVersion
    #   run: dotnet tool install -g GitVersion.Tool
    
    # - name: Run GitVersion
    #   id: gitversion
    #   run: dotnet gitversion /config GitVersion.yml /output buildserver

    # - name: Show GitVersion output
    #   run: 'echo "GitVersion Output: ${{ steps.gitversion.outputs.stdout }}"'

    # - name: Show GitVersion_SemVer
    #   run: 'echo "GitVersion_SemVert: ${{ steps.gitversion.outputs.GitVersion_SemVer }}"'

    # - name: Update NuGet package version
    #   run: |
    #     echo "Updating version to $VERSION in project files"
    #     find . -name '*.csproj' -print0 | xargs -0 sed -i "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/g"
    #   shell: bash
    #   env:
    #     VERSION: ${{ steps.gitversion.outputs.GitVersion_SemVer }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }} 

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --verbosity normal #--no-build
