name: GitVersion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitversion:
    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: 'src/EasySqlFlow.sln'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 #required for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool
    
    - name: Run GitVersion
      id: gitversion
      run: gitversion /output buildserver

    - name: Show GitVersion output
      run: 'echo "GitVersion Output: ${{ steps.gitversion.outputs.stdout }}"'

    - name: Update NuGet package version
      run: |
        version=$(echo "${{ steps.gitversion.outputs.stdout }}" | grep "AssemblySemVer:" | awk '{print $2}')
        echo "Updating version to $version in project files"
        find . -name '*.csproj' -print0 | xargs -0 sed -i "s/<Version>.*<\/Version>/<Version>$version<\/Version>/g"

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }} 

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --verbosity normal #--no-build
